Repository belf-kr/storage-service, pull requests merged in 2021-11, with the labels that each got.

#18 up: 빠른 시작 메뉴얼 작성
  README.md
Labels: documentation

#19 파일 추가시 userId 입력하는 기능 추가, 마이그레이션용 패키지 추가, requirements.txt 파일 간소화
  Application.py
  Manager/File/FileManager.py
  Models/File.py
  requirements.txt
Labels: new feature, modify

#21 로컬 테스트 환경 구축 위한 docker 코드 추가
  .gitignore
  .idea/.gitignore
  README.md
  docker-compose.yml
  docker/mysql/Dockerfile
  docker/mysql/init.sql
Labels: documentation, new feature

#22 실 서버 배포 자동화 구성
  .github/CODEOWNERS
  .github/workflows/aks-prod-deploy.yaml
  .github/workflows/aks-qa-deploy.yaml
  .github/workflows/aks-test-deploy.yaml
  Config/ApplicationConfig.py
  Config/UploadConfig.py
  Config/app_config.json
  Config/upload_config.json
  Dockerfile
  README.md
  docker-compose.yml
  k8s/prod-external.yaml
  k8s/prod-pvc.yaml
  k8s/prod.yaml
  k8s/qa-external.yaml
  k8s/qa-pvc.yaml
  k8s/qa.yaml
  k8s/test-external.yaml
  k8s/test.yaml
Labels: new feature, k8s

#24 Production 환경인 경우 플래그 값으로 환경변수 가져오는 기능으로 수정
  Config/DatabaseConfig.py
Labels: modify

#25 v0.1.1
  Config/DatabaseConfig.py
Labels: modify

#26 버전 정보 업데이트
  Config/ApplicationConfig.py
  Config/DatabaseConfig.py
Labels: bug

#29 코드 리펙터링 및 적절한 http status 값 반환 및 해더 처리
  .gitignore
  API/Delete.py
  API/Download.py
  API/Information.py
  API/Upload.py
  Application.py
  Config/db_config.json
  Manager/File/FileErrorCode.py
  Manager/File/FileManager.py
  Manager/Response/DownloadResponse/DownloadResponseManager.py
  Manager/Response/DownloadResponse/__init__.py
  Manager/Response/ResponseHeaderHelper.py
  Manager/Response/ResponseManager.py
  Manager/Response/UploadResponse/UploadResponseManager.py
  Manager/Response/UploadResponse/__init__.py
  Manager/Response/__init__.py
  Models/FileModel.py
  TortoiseRouter.py
Labels: new feature, modify, structure

#30 Refactoring & Bug Fix, JWT Authorization Feature, 스케일 업, k8s 헬스 체크 추가
  API/Default.py
  API/Delete.py
  API/Download.py
  API/Information.py
  API/Upload.py
  Application.py
  Common/CommonDefines.py
  Common/CommonPath.py
  Common/Converter.py
  Common/Path.py
  Common/Request/Body.py
  Common/Request/Headers.py
  Common/Request/Query.py
  Common/Request/__init__.py
  Common/UrlTool.py
  Common/__init__.py
  Config/ApplicationConfig.py
  Config/BaseConfig.py
  Config/DatabaseConfig.py
  Config/EnvironmentConfig.py
  Config/OAuthConfig.py
  Config/UploadConfig.py
  Config/__init__.py
  Config/local/app_config.json
  Config/local/db_config.json
  Config/local/upload_config.json
  Manager/File/FileErrorCode.py
  Manager/File/FileManager.py
  Manager/__init__.py
  Middleware/Authorization.py
  Middleware/__init__.py
  Models/FileModel.py
  Models/__init__.py
  config.json
  k8s/prod.yaml
  k8s/qa.yaml
  requirements.txt
Labels: bug, new feature, k8s, modify, structure

#31 201 응답에 Access-Control-Allow-Origin : * 헤더 추가
  API/Upload.py
  Application.py
Labels: bug, modify
