Repository belf-kr/storage-service, pull requests merged in 2021-12, with the labels that each got.

#36 README.md 참고해 즉시 실행 가능 하도록 설명 추가
  README.md
  docker-compose.yml
Labels: documentation

#35 버퍼 시스템을 사용하는 파일 업로드, 새로운 예외 처리 로직
  API/Delete.py
  API/Download.py
  API/Information.py
  API/Upload.py
  Common/Request/Body.py
  Common/Request/Headers.py
  Common/Request/Query.py
  Config/ApplicationConfig.py
  Config/local/db_config.json
  Manager/File/FileManager.py
  Middleware/Authorization.py
  Models/FileModel.py
  README.md
  test/.vscode/settings.json
  test/axios.min.js
  test/index.html
Labels: bug, modify, structure

#39 deprecated된 kubectl 명령어 변경, slack slack notification 메시지 표시되도록
  .github/workflows/aks-prod-deploy.yaml
  .github/workflows/aks-qa-deploy.yaml
  .github/workflows/aks-test-deploy.yaml
  API/Default.py
  Config/ApplicationConfig.py
Labels: bug, k8s

#40 v1.0.0
  .github/workflows/aks-prod-deploy.yaml
  .github/workflows/aks-qa-deploy.yaml
  .github/workflows/aks-test-deploy.yaml
  API/Default.py
  Config/ApplicationConfig.py
Labels: bug, k8s, modify

#41 Docker 환경에서 OAuth 인증서버에 HTTP 접근 가능하게 수정
  Config/ApplicationConfig.py
  Config/OAuthConfig.py
  Config/local/app_config.json
  README.md
Labels: bug
